// dim_customer - generated by src/export.py (do not edit by hand)
let
    Source = Csv.Document(
        File.Contents(DataFolder & "dim_customer.csv"),
        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
    ),
    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
    // Empty CSV fields -> null (otherwise numeric/logical conversion fails)
    Nulls = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, Table.ColumnNames(Promoted)),
    Typed = Table.TransformColumnTypes(Nulls, {
        {"customer_unique_id", type text},
        {"zip_code_prefix", type text},
        {"city", type text},
        {"state", type text},
        {"region", type text},
        {"lat", type number},
        {"lng", type number},
        {"geo_source", type text},
        {"first_purchase_date", type date},
        {"last_purchase_date", type date},
        {"lifetime_orders", Int64.Type},
        {"lifetime_revenue", Currency.Type},
        {"is_repeat_customer", type logical}
    }, "en-US")
in
    Typed
