// dim_date - generated by src/export.py (do not edit by hand)
let
    Source = Csv.Document(
        File.Contents(DataFolder & "dim_date.csv"),
        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
    ),
    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
    // Empty CSV fields -> null (otherwise numeric/logical conversion fails)
    Nulls = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, Table.ColumnNames(Promoted)),
    Typed = Table.TransformColumnTypes(Nulls, {
        {"date", type date},
        {"date_key", Int64.Type},
        {"year", Int64.Type},
        {"quarter", type text},
        {"year_quarter", type text},
        {"month_num", Int64.Type},
        {"month_name", type text},
        {"month_short", type text},
        {"year_month", type text},
        {"year_month_num", Int64.Type},
        {"month_start", type date},
        {"iso_week", Int64.Type},
        {"day_of_week_num", Int64.Type},
        {"day_name", type text},
        {"is_weekend", type logical},
        {"is_complete_month", type logical}
    }, "en-US")
in
    Typed
