// dim_product - generated by src/export.py (do not edit by hand)
let
    Source = Csv.Document(
        File.Contents(DataFolder & "dim_product.csv"),
        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
    ),
    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
    // Empty CSV fields -> null (otherwise numeric/logical conversion fails)
    Nulls = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, Table.ColumnNames(Promoted)),
    Typed = Table.TransformColumnTypes(Nulls, {
        {"product_id", type text},
        {"category", type text},
        {"category_pt", type text},
        {"product_weight_g", Int64.Type},
        {"product_length_cm", Int64.Type},
        {"product_height_cm", Int64.Type},
        {"product_width_cm", Int64.Type},
        {"product_volume_cm3", type number},
        {"product_photos_qty", Int64.Type},
        {"product_name_length", Int64.Type},
        {"product_description_length", Int64.Type}
    }, "en-US")
in
    Typed
