// dim_seller - generated by src/export.py (do not edit by hand)
let
    Source = Csv.Document(
        File.Contents(DataFolder & "dim_seller.csv"),
        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
    ),
    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
    // Empty CSV fields -> null (otherwise numeric/logical conversion fails)
    Nulls = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, Table.ColumnNames(Promoted)),
    Typed = Table.TransformColumnTypes(Nulls, {
        {"seller_id", type text},
        {"seller_label", type text},
        {"zip_code_prefix", type text},
        {"city", type text},
        {"state", type text},
        {"region", type text},
        {"lat", type number},
        {"lng", type number},
        {"geo_source", type text}
    }, "en-US")
in
    Typed
