// fact_orders - generated by src/export.py (do not edit by hand)
let
    Source = Csv.Document(
        File.Contents(DataFolder & "fact_orders.csv"),
        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
    ),
    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
    // Empty CSV fields -> null (otherwise numeric/logical conversion fails)
    Nulls = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, Table.ColumnNames(Promoted)),
    Typed = Table.TransformColumnTypes(Nulls, {
        {"order_id", type text},
        {"customer_unique_id", type text},
        {"date_key", Int64.Type},
        {"purchase_date", type date},
        {"order_purchase_timestamp", type datetime},
        {"order_status", type text},
        {"is_sale", type logical},
        {"has_items", type logical},
        {"is_delivered", type logical},
        {"is_late", type logical},
        {"is_multi_seller", type logical},
        {"is_repeat_purchase", type logical},
        {"customer_order_seq", Int64.Type},
        {"items_count", Int64.Type},
        {"products_count", Int64.Type},
        {"sellers_count", Int64.Type},
        {"items_price", Currency.Type},
        {"freight_total", Currency.Type},
        {"order_value", Currency.Type},
        {"payment_total", Currency.Type},
        {"main_payment_type", type text},
        {"payment_methods", Int64.Type},
        {"max_installments", Int64.Type},
        {"is_installment", type logical},
        {"used_voucher", type logical},
        {"installment_bucket", type text},
        {"installment_bucket_order", Int64.Type},
        {"order_approved_at", type datetime},
        {"order_delivered_carrier_date", type datetime},
        {"order_delivered_customer_date", type datetime},
        {"order_estimated_delivery_date", type date},
        {"approval_hours", type number},
        {"carrier_lead_days", type number},
        {"last_mile_days", type number},
        {"delivery_days", type number},
        {"promised_days", type number},
        {"delay_days", type number},
        {"delivery_bucket", type text},
        {"delivery_bucket_order", Int64.Type},
        {"flag_carrier_before_approval", type logical},
        {"flag_delivered_before_carrier", type logical},
        {"has_review", type logical},
        {"review_score", Int64.Type},
        {"review_count", Int64.Type},
        {"has_comment", type logical},
        {"review_response_hours", type number}
    }, "en-US")
in
    Typed
