// fact_order_items - generated by src/export.py (do not edit by hand)
let
    Source = Csv.Document(
        File.Contents(DataFolder & "fact_order_items.csv"),
        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
    ),
    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
    // Empty CSV fields -> null (otherwise numeric/logical conversion fails)
    Nulls = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, Table.ColumnNames(Promoted)),
    Typed = Table.TransformColumnTypes(Nulls, {
        {"order_id", type text},
        {"order_item_id", Int64.Type},
        {"product_id", type text},
        {"seller_id", type text},
        {"customer_unique_id", type text},
        {"date_key", Int64.Type},
        {"purchase_date", type date},
        {"shipping_limit_date", type datetime},
        {"price", Currency.Type},
        {"freight_value", Currency.Type},
        {"item_total", Currency.Type},
        {"freight_share", type number},
        {"freight_gt_price", type logical},
        {"order_status", type text},
        {"is_sale", type logical},
        {"is_delivered", type logical},
        {"is_late", type logical},
        {"delivery_days", type number},
        {"review_score", Int64.Type},
        {"is_multi_seller", type logical}
    }, "en-US")
in
    Typed
