table dim_date
	lineageTag: e896da35-79a9-41bf-ba21-2589f1405b6d
	dataCategory: Time

	column date
		dataType: dateTime
		isKey
		formatString: Long Date
		lineageTag: 69742f58-ab74-4db4-80ef-7788d8ebd26d
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column date_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 505307cb-84a6-4a87-ad7e-4a3da59b3639
		summarizeBy: none
		sourceColumn: date_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column year
		dataType: int64
		formatString: 0
		lineageTag: 58395ddf-d687-426b-a01e-3884fdba1a31
		summarizeBy: none
		sourceColumn: year

		annotation SummarizationSetBy = User

	column quarter
		dataType: string
		lineageTag: e022a686-2670-4e4c-8ff5-08ca8e811ab1
		summarizeBy: none
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column year_quarter
		dataType: string
		lineageTag: 4502dc38-3376-4a1c-b0b4-5202428763e3
		summarizeBy: none
		sourceColumn: year_quarter

		annotation SummarizationSetBy = Automatic

	column month_num
		dataType: int64
		formatString: 0
		lineageTag: 0386526b-2023-495a-9f82-b80a89542191
		summarizeBy: none
		sourceColumn: month_num

		annotation SummarizationSetBy = User

	column month_name
		dataType: string
		lineageTag: f2a517db-dcb6-4e62-99cb-fdd1f04af211
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: month_num

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column month_short
		dataType: string
		lineageTag: 2f1298d5-08ea-444f-ab75-cd696e62e37c
		summarizeBy: none
		sourceColumn: month_short
		sortByColumn: month_num

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: string
		lineageTag: 0f1a73f0-8f4f-4b20-b95f-bec6a7f4e12f
		summarizeBy: none
		sourceColumn: year_month
		sortByColumn: year_month_num

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column year_month_num
		dataType: int64
		formatString: 0
		lineageTag: d2d9db1a-fdc8-4013-9c86-9ee7fdc3b6ba
		summarizeBy: none
		sourceColumn: year_month_num

		annotation SummarizationSetBy = User

	column month_start
		dataType: dateTime
		formatString: Long Date
		lineageTag: cc961c6d-7b61-4cef-aa67-fd5cfc5e27ed
		summarizeBy: none
		sourceColumn: month_start

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column iso_week
		dataType: int64
		formatString: 0
		lineageTag: 64320a61-b795-45b7-acba-33e706509b7e
		summarizeBy: none
		sourceColumn: iso_week

		annotation SummarizationSetBy = User

	column day_of_week_num
		dataType: int64
		formatString: 0
		lineageTag: 3938ee0b-a675-4a07-aac4-f4f663b7f6aa
		summarizeBy: none
		sourceColumn: day_of_week_num

		annotation SummarizationSetBy = User

	column day_name
		dataType: string
		lineageTag: 908e7ca8-a875-48a6-aaa3-f898ba12fe37
		summarizeBy: none
		sourceColumn: day_name
		sortByColumn: day_of_week_num

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 4484d37b-2525-4d8c-aca1-8310644dd55b
		summarizeBy: none
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column is_complete_month
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: cd744705-c036-4f67-a4cf-a90ba32596d8
		summarizeBy: none
		sourceColumn: is_complete_month

		annotation SummarizationSetBy = Automatic

	partition dim_date = m
		mode: import
		source =
				// dim_date - generated by src/export.py (do not edit by hand)
				let
				    Source = Csv.Document(
				        File.Contents(DataFolder & "dim_date.csv"),
				        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
				    ),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    // Empty CSV fields -> null (otherwise numeric/logical conversion fails)
				    Nulls = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, Table.ColumnNames(Promoted)),
				    Typed = Table.TransformColumnTypes(Nulls, {
				        {"date", type date},
				        {"date_key", Int64.Type},
				        {"year", Int64.Type},
				        {"quarter", type text},
				        {"year_quarter", type text},
				        {"month_num", Int64.Type},
				        {"month_name", type text},
				        {"month_short", type text},
				        {"year_month", type text},
				        {"year_month_num", Int64.Type},
				        {"month_start", type date},
				        {"iso_week", Int64.Type},
				        {"day_of_week_num", Int64.Type},
				        {"day_name", type text},
				        {"is_weekend", type logical},
				        {"is_complete_month", type logical}
				    }, "en-US")
				in
				    Typed

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

