table dim_customer
	lineageTag: 57d3ccbf-f7a9-4f2a-a348-5baddfbc9d68

	column customer_unique_id
		dataType: string
		lineageTag: 7f8c8df5-b3a8-49bf-a130-650d7362b31f
		summarizeBy: none
		sourceColumn: customer_unique_id

		annotation SummarizationSetBy = Automatic

	column zip_code_prefix
		dataType: string
		lineageTag: da216b68-69c1-49ad-9db1-6e04d392cdab
		summarizeBy: none
		sourceColumn: zip_code_prefix

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: 6c049e63-aa85-42d6-9bc3-1c6bdba23615
		dataCategory: City
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: b0763339-cf92-44c6-b23c-a575df50910d
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: bc99b861-eee6-41a9-b1ed-0f5ec2991a0d
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column lat
		dataType: double
		lineageTag: 08ceb119-13c8-4bdc-8b0f-79ad107461de
		dataCategory: Latitude
		summarizeBy: none
		sourceColumn: lat

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column lng
		dataType: double
		lineageTag: fb791561-59a2-40b0-a2fd-6071bdd73ec8
		dataCategory: Longitude
		summarizeBy: none
		sourceColumn: lng

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column geo_source
		dataType: string
		lineageTag: f23ffc1d-d2b8-47bf-b3a3-960112abfca4
		summarizeBy: none
		sourceColumn: geo_source

		annotation SummarizationSetBy = Automatic

	column first_purchase_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: a101eb28-6143-4ebc-8f6e-a71db0c4178b
		summarizeBy: none
		sourceColumn: first_purchase_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column last_purchase_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 971414a2-489e-4328-b031-0d0652884222
		summarizeBy: none
		sourceColumn: last_purchase_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column lifetime_orders
		dataType: int64
		formatString: 0
		lineageTag: 0aecc2a4-0613-48a5-84c6-811c0a85ebcb
		summarizeBy: sum
		sourceColumn: lifetime_orders

		annotation SummarizationSetBy = Automatic

	column lifetime_revenue
		dataType: decimal
		formatString: \$#,0.###############;-\$#,0.###############;\$#,0.###############
		lineageTag: 3daedceb-b223-4dd2-9ff2-b47a4db08838
		summarizeBy: sum
		sourceColumn: lifetime_revenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-MX"}

	column is_repeat_customer
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 6b160de3-5c15-4f51-8327-b07692a964fc
		summarizeBy: none
		sourceColumn: is_repeat_customer

		annotation SummarizationSetBy = Automatic

	partition dim_customer = m
		mode: import
		source =
				// dim_customer - generated by src/export.py (do not edit by hand)
				let
				    Source = Csv.Document(
				        File.Contents(DataFolder & "dim_customer.csv"),
				        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
				    ),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    // Empty CSV fields -> null (otherwise numeric/logical conversion fails)
				    Nulls = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, Table.ColumnNames(Promoted)),
				    Typed = Table.TransformColumnTypes(Nulls, {
				        {"customer_unique_id", type text},
				        {"zip_code_prefix", type text},
				        {"city", type text},
				        {"state", type text},
				        {"region", type text},
				        {"lat", type number},
				        {"lng", type number},
				        {"geo_source", type text},
				        {"first_purchase_date", type date},
				        {"last_purchase_date", type date},
				        {"lifetime_orders", Int64.Type},
				        {"lifetime_revenue", Currency.Type},
				        {"is_repeat_customer", type logical}
				    }, "en-US")
				in
				    Typed

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

