table dim_seller
	lineageTag: 37285eed-6dbd-4313-afc4-c51cb74f434e

	column seller_id
		dataType: string
		lineageTag: c81ded53-7889-4d92-acf9-49b3cc340114
		summarizeBy: none
		sourceColumn: seller_id

		annotation SummarizationSetBy = Automatic

	column zip_code_prefix
		dataType: string
		lineageTag: 58887042-653e-43eb-971b-fa14825478ef
		summarizeBy: none
		sourceColumn: zip_code_prefix

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: 30a2e98b-8a95-415b-8f4c-0604d0be2924
		dataCategory: City
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: a4b940a1-b1e4-47c4-b952-313a2b35069e
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 47ed0a60-9b8c-4289-be3a-7757e26d72b8
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column lat
		dataType: double
		lineageTag: c9b89762-7184-4a67-a052-18d4e75f499e
		dataCategory: Latitude
		summarizeBy: none
		sourceColumn: lat

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column lng
		dataType: double
		lineageTag: 3f5b3953-a4ab-4cbd-8328-dd36d14e8fb1
		dataCategory: Longitude
		summarizeBy: none
		sourceColumn: lng

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column geo_source
		dataType: string
		lineageTag: 2b71a0d2-f159-4bc5-a502-4aa56b029b4d
		summarizeBy: none
		sourceColumn: geo_source

		annotation SummarizationSetBy = Automatic

	column seller_label
		dataType: string
		lineageTag: 70deaabb-6a3e-4b4c-a068-c0ad07f86549
		summarizeBy: none
		sourceColumn: seller_label

		annotation SummarizationSetBy = Automatic

	partition dim_seller = m
		mode: import
		source =
				// dim_seller - generated by src/export.py (do not edit by hand)
				let
				    Source = Csv.Document(
				        File.Contents(DataFolder & "dim_seller.csv"),
				        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
				    ),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    // Empty CSV fields -> null (otherwise numeric/logical conversion fails)
				    Nulls = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, Table.ColumnNames(Promoted)),
				    Typed = Table.TransformColumnTypes(Nulls, {
				        {"seller_id", type text},
				        {"seller_label", type text},
				        {"zip_code_prefix", type text},
				        {"city", type text},
				        {"state", type text},
				        {"region", type text},
				        {"lat", type number},
				        {"lng", type number},
				        {"geo_source", type text}
				    }, "en-US")
				in
				    Typed

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

