table dim_product
	lineageTag: 69d1d4c5-32bb-42e3-9416-3625de3b9c0f

	column product_id
		dataType: string
		lineageTag: 02655a11-22b1-4258-91a5-c0da45c1a125
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: b43ca9c1-9f86-4b52-ad21-fd92d37bc1a6
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column category_pt
		dataType: string
		lineageTag: c894df5e-59ca-4c91-bf94-c171fe1f76a7
		summarizeBy: none
		sourceColumn: category_pt

		annotation SummarizationSetBy = Automatic

	column product_weight_g
		dataType: int64
		formatString: 0
		lineageTag: 604aaf45-d43b-4ff2-a727-860d5871bde7
		summarizeBy: none
		sourceColumn: product_weight_g

		annotation SummarizationSetBy = Automatic

	column product_length_cm
		dataType: int64
		formatString: 0
		lineageTag: 0893a2b4-729e-4a3a-8c64-09b6843dec20
		summarizeBy: none
		sourceColumn: product_length_cm

		annotation SummarizationSetBy = Automatic

	column product_height_cm
		dataType: int64
		formatString: 0
		lineageTag: 1b45be27-affe-43b4-81c4-46174b5e2558
		summarizeBy: none
		sourceColumn: product_height_cm

		annotation SummarizationSetBy = Automatic

	column product_width_cm
		dataType: int64
		formatString: 0
		lineageTag: 33bfaa94-b4a5-486f-877f-6fea2cdd2765
		summarizeBy: none
		sourceColumn: product_width_cm

		annotation SummarizationSetBy = Automatic

	column product_volume_cm3
		dataType: double
		lineageTag: 64b20caf-62e7-4511-8528-3eb415705d3d
		summarizeBy: none
		sourceColumn: product_volume_cm3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column product_photos_qty
		dataType: int64
		formatString: 0
		lineageTag: 50f69b23-3531-4124-ac70-61302f15ee25
		summarizeBy: none
		sourceColumn: product_photos_qty

		annotation SummarizationSetBy = Automatic

	column product_name_length
		dataType: int64
		formatString: 0
		lineageTag: 3106cce3-8858-4a27-84da-5b340be334ef
		summarizeBy: none
		sourceColumn: product_name_length

		annotation SummarizationSetBy = Automatic

	column product_description_length
		dataType: int64
		formatString: 0
		lineageTag: 217bcfe8-e6de-4525-8279-71008ee98083
		summarizeBy: none
		sourceColumn: product_description_length

		annotation SummarizationSetBy = Automatic

	partition dim_product = m
		mode: import
		source =
				// dim_product - generated by src/export.py (do not edit by hand)
				let
				    Source = Csv.Document(
				        File.Contents(DataFolder & "dim_product.csv"),
				        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
				    ),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    // Empty CSV fields -> null (otherwise numeric/logical conversion fails)
				    Nulls = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, Table.ColumnNames(Promoted)),
				    Typed = Table.TransformColumnTypes(Nulls, {
				        {"product_id", type text},
				        {"category", type text},
				        {"category_pt", type text},
				        {"product_weight_g", Int64.Type},
				        {"product_length_cm", Int64.Type},
				        {"product_height_cm", Int64.Type},
				        {"product_width_cm", Int64.Type},
				        {"product_volume_cm3", type number},
				        {"product_photos_qty", Int64.Type},
				        {"product_name_length", Int64.Type},
				        {"product_description_length", Int64.Type}
				    }, "en-US")
				in
				    Typed

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

