"""
Export the star schema for Power BI and document it.

Outputs
-------
data/processed/<table>.csv     UTF-8, ISO dates, '.' decimal separator
reports/cleaning_log.md        every cleaning action and the rows it touched
reports/data_model.md          ER diagram (Mermaid), grain, integrity checks, data dictionary
"""
from __future__ import annotations

import logging
from datetime import datetime

import pandas as pd

from src import config as cfg
from src.clean import CleaningLog
from src.dictionary import COLUMN_DOCS, TABLE_DOCS
from src.model import PRIMARY_KEYS, RELATIONSHIPS

logger = logging.getLogger(__name__)


def export_csv(model: dict[str, pd.DataFrame]) -> None:
    cfg.PROCESSED_DIR.mkdir(parents=True, exist_ok=True)
    for name, df in model.items():
        out = df.copy()
        # Dates without time are written as YYYY-MM-DD so Power BI types them as Date
        for col in out.select_dtypes("datetime").columns:
            if (out[col].dropna().dt.normalize() == out[col].dropna()).all():
                out[col] = out[col].dt.strftime("%Y-%m-%d")
        path = cfg.PROCESSED_DIR / f"{name}.csv"
        out.to_csv(path, index=False, encoding="utf-8", date_format="%Y-%m-%d %H:%M:%S")
        logger.info("Exported %-17s -> %s (%.1f MB)", name,
                    path.relative_to(cfg.ROOT_DIR), path.stat().st_size / 1e6)


def _mermaid() -> str:
    lines = ["```mermaid", "erDiagram"]
    labels = {"dim_customer": "buys", "dim_date": "on", "dim_product": "sold as",
              "dim_seller": "sold by"}
    for fact, fk, dim, _ in RELATIONSHIPS:
        lines.append(f'    {dim} ||--o{{ {fact} : "{labels[dim]} ({fk})"')
    lines.append("```")
    return "\n".join(lines)


def write_cleaning_log(log: CleaningLog) -> None:
    df = log.to_frame()
    md = [
        "# Cleaning Log",
        "",
        f"*Generated by `python -m src.main` on {datetime.now():%Y-%m-%d %H:%M}.*",
        "",
        "Every transformation applied between the raw files and the Power BI model, in order. "
        "Rows are deleted only when they are exact duplicates or physically impossible; "
        "all other issues are corrected or flagged.",
        "",
        df.to_markdown(index=False, intfmt=","),
        "",
    ]
    (cfg.REPORTS_DIR / "cleaning_log.md").write_text("\n".join(md), encoding="utf-8", newline="\n")


def write_data_model_doc(model: dict[str, pd.DataFrame], checks: pd.DataFrame) -> None:
    md = [
        "# Data Model - Star Schema",
        "",
        f"*Generated by `python -m src.main` on {datetime.now():%Y-%m-%d %H:%M}.*",
        "",
        "## Diagram",
        "",
        "Two fact tables at different grains share the conformed dimensions `dim_customer` "
        "and `dim_date`. All relationships are **one-to-many, single direction**.",
        "",
        _mermaid(),
        "",
        "## Tables",
        "",
    ]
    overview = pd.DataFrame([
        {"table": t, "grain": TABLE_DOCS[t][0], "primary key": ", ".join(PRIMARY_KEYS[t]),
         "rows": len(model[t]), "columns": model[t].shape[1], "purpose": TABLE_DOCS[t][1]}
        for t in model
    ])
    md += [overview.to_markdown(index=False, intfmt=","), "",
           "## Integrity checks", "",
           "The pipeline stops if any of these fails.", "",
           checks.to_markdown(index=False), "",
           "## Modelling notes", "",
           "- **Revenue = sum of item `price`** for sales (status not canceled/unavailable). "
           "Freight and installment interest are reported separately.",
           "- `fact_order_items` repeats order context (`review_score`, `is_late`, "
           "`delivery_days`) on each item so sellers can be analysed without "
           "bidirectional filters. In DAX, aggregate these columns **per order** "
           "(e.g. `AVERAGEX(SUMMARIZE(fact_order_items, fact_order_items[order_id], "
           "fact_order_items[review_score]), [review_score])`).",
           "- For seller ratings, orders with several sellers (`is_multi_seller`) share one "
           "review; exclude them when a strict attribution is required.",
           "- Use `dim_date[is_complete_month]` to restrict trends and MoM % to complete months.",
           "",
           "## Data dictionary", ""]
    for t, df in model.items():
        dd = pd.DataFrame({
            "column": df.columns,
            "type": [str(x) for x in df.dtypes],
            "% null": (100 * df.isna().mean()).round(2).to_numpy(),
            "description": [COLUMN_DOCS.get(c, "") for c in df.columns],
        })
        md += [f"### {t}", "", f"*Grain: {TABLE_DOCS[t][0]}.*", "",
               dd.to_markdown(index=False), ""]
    (cfg.REPORTS_DIR / "data_model.md").write_text("\n".join(md), encoding="utf-8", newline="\n")


# --------------------------------------------------------------------------- #
# Power Query (M) scripts with explicit column types
# --------------------------------------------------------------------------- #
# Money columns use Fixed Decimal (Currency.Type) to avoid floating-point drift in sums
MONEY_COLUMNS = {"price", "freight_value", "item_total", "items_price", "freight_total",
                 "order_value", "payment_total", "lifetime_revenue"}


def _m_type(col: str, s: pd.Series) -> str:
    if col in MONEY_COLUMNS:
        return "Currency.Type"
    if col == "date_key" or col.endswith("_num") or col in ("year", "iso_week"):
        return "Int64.Type"
    if pd.api.types.is_bool_dtype(s):
        return "type logical"
    if pd.api.types.is_integer_dtype(s):
        return "Int64.Type"
    if pd.api.types.is_float_dtype(s):
        return "type number"
    if pd.api.types.is_datetime64_any_dtype(s):
        d = s.dropna()
        return "type date" if (d.dt.normalize() == d).all() else "type datetime"
    return "type text"


def write_power_query(model: dict[str, pd.DataFrame]) -> None:
    """
    One .pq file per table, to paste in Power BI > Transform data > Advanced Editor.
    Types are declared explicitly with the en-US culture, so the result does not
    depend on the regional settings of the machine opening the report.
    """
    out_dir = cfg.ROOT_DIR / "powerbi" / "power_query"
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "DataFolder.pq").write_text(
        '// Parameter: folder that contains the processed CSVs (keep the trailing backslash)\n'
        '"C:\\path\\to\\olist-bi-dashboard\\data\\processed\\" '
        'meta [IsParameterQuery=true, Type="Text", IsParameterQueryRequired=true]\n',
        encoding="utf-8", newline="\n")

    for name, df in model.items():
        types = ",\n        ".join(f'{{"{c}", {_m_type(c, df[c])}}}' for c in df.columns)
        m = f"""// {name} - generated by src/export.py (do not edit by hand)
let
    Source = Csv.Document(
        File.Contents(DataFolder & "{name}.csv"),
        [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
    ),
    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
    // Empty CSV fields -> null (otherwise numeric/logical conversion fails)
    Nulls = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, Table.ColumnNames(Promoted)),
    Typed = Table.TransformColumnTypes(Nulls, {{
        {types}
    }}, "en-US")
in
    Typed
"""
        (out_dir / f"{name}.pq").write_text(m, encoding="utf-8", newline="\n")
    logger.info("Power Query scripts written to %s", out_dir.relative_to(cfg.ROOT_DIR))
