"""
Run sql/business_queries.sql on the exported star schema with DuckDB.

Usage:
    python -m src.run_sql

Each query is labelled with a header line "-- name: <id> | <question>".
Results are written to reports/sql_results.md (and printed), so the
answers in the executive summary can be traced to a reproducible query.
"""
from __future__ import annotations

import logging
import re
from datetime import datetime

import duckdb
import pandas as pd

from src import config as cfg

logger = logging.getLogger(__name__)
SQL_FILE = cfg.ROOT_DIR / "sql" / "business_queries.sql"
TABLES = ["fact_orders", "fact_order_items", "dim_customer", "dim_product",
          "dim_seller", "dim_date"]
HEADER = re.compile(r"^-- name:\s*(\S+)\s*\|\s*(.+)$", re.MULTILINE)


def parse_queries(sql_text: str) -> list[tuple[str, str, str]]:
    """Split the file into (id, question, sql) using the '-- name:' headers."""
    marks = list(HEADER.finditer(sql_text))
    out = []
    for i, m in enumerate(marks):
        end = marks[i + 1].start() if i + 1 < len(marks) else len(sql_text)
        body = sql_text[m.end():end].strip().rstrip(";")
        out.append((m.group(1), m.group(2).strip(), body))
    return out


def connect() -> duckdb.DuckDBPyConnection:
    con = duckdb.connect()
    for t in TABLES:
        path = cfg.PROCESSED_DIR / f"{t}.csv"
        if not path.exists():
            raise FileNotFoundError(f"{path} not found. Run `python -m src.main` first.")
        con.execute(f"CREATE VIEW {t} AS SELECT * FROM read_csv_auto('{path.as_posix()}', header=true)")
    return con


def run_all() -> dict[str, pd.DataFrame]:
    con = connect()
    results, md = {}, [
        "# SQL Results",
        "",
        f"*Generated by `python -m src.run_sql` on {datetime.now():%Y-%m-%d %H:%M}. "
        "Queries: [`sql/business_queries.sql`](../sql/business_queries.sql).*",
        "",
    ]
    for qid, question, sql in parse_queries(SQL_FILE.read_text(encoding="utf-8")):
        df = con.execute(sql).df()
        results[qid] = df
        logger.info("%-26s %4d rows", qid, len(df))
        md += [f"## {qid}", "", f"**{question}**", "",
               df.to_markdown(index=False, floatfmt=",.2f"), ""]
    (cfg.REPORTS_DIR / "sql_results.md").write_text("\n".join(md), encoding="utf-8")
    return results


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(levelname)s | %(message)s")
    pd.set_option("display.width", 200)
    for qid, df in run_all().items():
        print(f"\n=== {qid} ===\n{df.to_string(index=False)}")
